spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3336/oops?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: well1995
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  typeAliasesPackage: com.github.wellch4n.oops