apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{sandboxName}}"
  namespace: "{{namespace}}"
  labels:
    oops.type: sandbox
    oops.sandbox.kind: persistent
    oops.sandbox.id: "{{sandboxId}}"
    oops.sandbox.image: alpine-mate
    oops.sandbox.created-by: "{{createdBy}}"
  annotations:
    oops.sandbox.name: "{{name}}"
    oops.sandbox.image: "linuxserver/webtop:alpine-mate"
    oops.sandbox.cpu-request: "{{cpuRequest}}"
    oops.sandbox.cpu-limit: "{{cpuLimit}}"
    oops.sandbox.memory-request: "{{memoryRequest}}"
    oops.sandbox.memory-limit: "{{memoryLimit}}"
spec:
  serviceName: "{{sandboxName}}"
  replicas: 1
  selector:
    matchLabels:
      oops.sandbox.id: "{{sandboxId}}"
  template:
    metadata:
      labels:
        oops.type: sandbox
        oops.sandbox.kind: persistent
        oops.sandbox.id: "{{sandboxId}}"
        oops.sandbox.image: alpine-mate
        oops.sandbox.created-by: "{{createdBy}}"
      annotations:
        oops.sandbox.name: "{{name}}"
        oops.sandbox.image: "linuxserver/webtop:alpine-mate"
        oops.sandbox.cpu-request: "{{cpuRequest}}"
        oops.sandbox.cpu-limit: "{{cpuLimit}}"
        oops.sandbox.memory-request: "{{memoryRequest}}"
        oops.sandbox.memory-limit: "{{memoryLimit}}"
    spec:
      restartPolicy: Always
      securityContext: {}
      containers:
        - name: sandbox
          image: linuxserver/webtop:alpine-mate
          imagePullPolicy: IfNotPresent
          securityContext:
            seccompProfile:
              type: Unconfined
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Asia/Shanghai
            - name: SUBFOLDER
              value: /
            - name: TITLE
              value: "{{name}}"
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
            - containerPort: 3001
              name: https
              protocol: TCP
          resources:
            requests:
              cpu: "{{cpuRequest}}"
              memory: "{{memoryRequest}}"
            limits:
              cpu: "{{cpuLimit}}"
              memory: "{{memoryLimit}}"
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /dev/shm
              name: dshm
      volumes:
        - name: config
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: "{{sandboxName}}"
  namespace: "{{namespace}}"
spec:
  selector:
    oops.sandbox.id: "{{sandboxId}}"
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: https
      port: 3001
      protocol: TCP
      targetPort: 3001
  sessionAffinity: None
  type: ClusterIP
