spring:
  application:
    name: oops
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/oops?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
    username: root
    password: well1995
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration/mysql
    baseline-on-migrate: true
    baseline-version: 1
